#!/bin/sh

# Configuration
feh --bg-scale ~/.background.jpg
setxkbmap es
wmname LG3D
xsetroot -cursor_name left_ptr
# numlockx

# Background
dunst -conf ~/.dunstrc &
nm-applet &
# ~/dotfiles/scripts/xroot.sh &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
