let mapleader = "\<Space>"

" Plugins
call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Plug 'junegunn/fzf.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'morhetz/gruvbox'
Plug 'altercation/vim-colors-solarized'
Plug 'itchyny/lightline.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-surround'
Plug 'mattn/emmet-vim'
Plug 'tomtom/tcomment_vim'
Plug 'sheerun/vim-polyglot'
Plug 'vim-syntastic/syntastic'
Plug 'preservim/nerdtree'
" Language specific
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

" Basic vim
set number
syntax on
set tabstop=4
set autoindent
set expandtab
set softtabstop=4
set cursorline
set laststatus=2
set noshowmode
set autochdir

" Color scheme
set t_Co=256
if has('gui_running')
        set guioptions-=m
        set guioptions-=T
        set guioptions-=r
        set guioptions-=L
        set guifont=Source\ Code\ Pro\ 9
        colorscheme gruvbox
        set background=light
else
        colorscheme gruvbox
        set background=dark
endif

" Plugins configuration
let g:lightline = { 'colorscheme': 'solarized', }

let g:fzf_buffers_jump = 1

" Reload
map <silent> <Leader>r :source ~/.vimrc<CR>:PlugInstall<CR>:bdelete<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Keybindings
" nnoremap <C-p> :GFiles<CR>
" nnoremap <C-g> :Rg<CR>
nnoremap <silent> <leader>f :CtrlPCurFile<CR>
nnoremap <silent> <leader>b :CtrlPBuffer<CR>
nnoremap <silent> <leader>n :NERDTreeToggle<CR>

" Startup
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
