#!/bin/sh

bspc config border_width 3
bspc config window_gap 0

bspc config focused_border_color "#FF0000"
bspc config active_border_color "#20639B"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

if [[ $(hostname) == 'gdesktop' ]]; then
  bspc monitor HDMI-0 -d I II III
  bspc monitor HDMI-1 -d IV V VI VII
  bspc monitor DVI-D-0 -d VIII IX X
else
 bspc monitor -d I II III IV V VI VII VIII IX X
fi

# bspc rule -a scratchpad state=floating
bspc rule -a Zathura state=tiled
