set number
set noshowcmd
set clipboard=unnamed
set hidden
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set nowrap
set cursorline
set laststatus=2
set noshowmode
set autoindent
set autochdir
set autoread
set nobackup
set nowritebackup
set noswapfile
set updatetime=300
set cmdheight=2
set shortmess+=c
set signcolumn=yes
set colorcolumn=120
set ignorecase
set smartcase
set termguicolors
set autoread
set scrolloff=2
set sidescrolloff=5
