#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color
ORANGE='\033[0;33m'

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    echo "usage: pomo       25 minute cycle"
    echo -e "   or: pomo [break]['_message_']  see options below\n"
    echo "Options:"
    echo "  d: timer duration in minutes"
    echo "  s: 05 minute break"
    echo "  l:  15 minute break"
    echo "  message: Your message to display"
    return
fi

if [[ "$1" == "-v" ]] || [[ "$1" == "--version" ]]; then
    echo -e "${ORANGE}POMODORO TIMER BY RUKY"
    echo "  v: 1"
    echo "  twitter: @justruky"
    echo "  blog: rukshn.github.io"
    echo -e "  email: arkruka[@]gmail.com"
    return
fi

TITLE="Pomodoro timer"
TIMER=1500

while :
do
    case "$1" in
        -d | --duration)
            TIMER=$(($2*60))
            shift 2
            ;;
        -l | --long-break)
            MESSAGE="Long break over"
            TIMER=900
            shift
            ;;
        -s | --short-break)
            MESSAGE="Short break over"
            TIMER=300
            shift
            ;;
        -k | --kill)
            killall pomo
            return 0
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            return 1
            ;;
        *)  # No more options
            break
            ;;
    esac
done

if [ -n "$1" ]; then
    MESSAGE="$1"
elif [ -z "$MESSAGE" ]; then
    MESSAGE="Break!"
fi

echo -e "${RED}Timer set for ${ORANGE}$(($TIMER/60)) ${RED}minutes"

sleep $TIMER && \
    notify-send "$TITLE" "$MESSAGE" && \
    paplay ~/.notification.ogg &
