#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color
ORANGE='\033[0;33m'

TITLE="Timer"
MESSAGE="..."
TIMER=1500

while :
do
    case "$1" in
        -t | --timer)
            TIMER=$2
            MESSAGE=$3
            shift 3
            ;;
        -p | --pomodore)
            TITLE="Pomodore timer"
            MESSAGE="Pomodore over"
            TIMER=1500
            shift
            ;;
        -l | --long-break)
            TITLE="Pomodore timer"
            MESSAGE="Long break over"
            TIMER=900
            shift
            ;;
        -s | --short-break)
            TITLE="Pomodore timer"
            MESSAGE="Short break over"
            TIMER=300
            shift
            ;;
        -k | --kill)
            killall t
            return 0
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            return 1
            ;;
        *)  # No more options
            break
            ;;
    esac
done

echo -e "${RED}Timer set for ${ORANGE}$(($TIMER/60)) ${RED}minutes"

sleep $TIMER && \
    notify-send "$TITLE" "$MESSAGE" && \
    paplay ~/.notification.ogg &
