#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\[\033[01;32m\]\u\[\033[01;34m\]::\[\033[01;31m\]\h \[\033[00;34m\]{ \[\033[01;34m\]\w \[\033[00;34m\]}\[\033[01;32m\]-> \[\033[00m\]'

alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
function cdl { cd "$1"; ll;}
#PS1='[\u@\h \W]\$ '

export PATH=$HOME/Scripts:$PATH
